In [7]:
%cd ~/Documents/cvd-predictor/
from sklearnex import patch_sklearn
patch_sklearn()
import polars as pl
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier
from CVD.utils import get_metrics
from sklearn.model_selection import cross_val_score
import optuna
from xgboost import XGBClassifier
from sklearn.model_selection import StratifiedKFold, cross_val_score
from sklearn.metrics import f1_score
import pickle

C:\Users\timea\Documents\cvd-predictor

c:\Python311\Lib\site-packages\IPython\core\magics\osm.py:393: UserWarning: This is now an optional IPython functionality, using bookmarks requires you to install the `pickleshare` library.
  bkms = self.shell.db.get('bookmarks', {})
c:\Python311\Lib\site-packages\IPython\core\magics\osm.py:417: UserWarning: This is now an optional IPython functionality, setting dhist requires you to install the `pickleshare` library.
  self.shell.db['dhist'] = compress_dhist(dhist)[-100:]
Intel(R) Extension for Scikit-learn* enabled (https://github.com/uxlfoundation/scikit-learn-intelex)

In [8]:
df: pl.DataFrame = pl.read_parquet("data/intermediate/heart_cdc_2023_cleaned.parquet")

In [9]:
X: pl.DataFrame = df.drop(["CVD"])
y: pl.Series = df["CVD"]

# scaler = StandardScaler()
# X[X.columns] = scaler.fit_transform(X)

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

In [10]:
def objective(trial):
    params = {
        "n_estimators": trial.suggest_int("n_estimators", 100, 1000),
        "max_depth": trial.suggest_int("max_depth", 3, 15),
        "learning_rate": trial.suggest_loguniform("learning_rate", 0.01, 0.3),
        "subsample": trial.suggest_uniform("subsample", 0.5, 1.0),
        "colsample_bytree": trial.suggest_uniform("colsample_bytree", 0.5, 1.0),
        "gamma": trial.suggest_loguniform("gamma", 1e-8, 1.0),
        "min_child_weight": trial.suggest_int("min_child_weight", 1, 10),
        "scale_pos_weight": trial.suggest_loguniform("scale_pos_weight", 1e-2, 10),  # For handling imbalance
        "random_state": 42,
        "eval_metric": "logloss",
        "use_label_encoder": False,
    }

    skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
    model = XGBClassifier(**params)
    scores = cross_val_score(model, X_train, y_train, cv=skf, scoring="f1", n_jobs=-1)
    return scores.mean()

# Create Optuna study and optimize
study = optuna.create_study(direction="maximize")
study.optimize(objective, n_trials=100)

print("Best trial:")
best_trial = study.best_trial
print(f"  F1 Score: {best_trial.value}")
print("  Params:")
for key, value in best_trial.params.items():
    print(f"    {key}: {value}")

[I 2025-04-02 02:40:19,162] A new study created in memory with name: no-name-0376bf7f-3fdf-4959-b37d-0de15d44be7d
C:\Users\timea\AppData\Local\Temp\ipykernel_13396\4213741627.py:5: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  "learning_rate": trial.suggest_loguniform("learning_rate", 0.01, 0.3),
C:\Users\timea\AppData\Local\Temp\ipykernel_13396\4213741627.py:6: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  "subsample": trial.suggest_uniform("subsample", 0.5, 1.0),
C:\Users\timea\AppData\Local\Temp\ipykernel_13396\4213741627.py:7: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  "colsample_bytree": trial.suggest_uniform("colsample_bytree", 0.5, 1.0),
C:\Users\timea\AppData\Local\Temp\ipykernel_13396\4213741627.py:8: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  "gamma": trial.suggest_loguniform("gamma", 1e-8, 1.0),
C:\Users\timea\AppData\Local\Temp\ipykernel_13396\4213741627.py:10: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  "scale_pos_weight": trial.suggest_loguniform("scale_pos_weight", 1e-2, 10),  # For handling imbalance
[I 2025-04-02 02:40:24,666] Trial 0 finished with value: 0.6688870406382103 and parameters: {'n_estimators': 128, 'max_depth': 14, 'learning_rate': 0.10636832427280554, 'subsample': 0.7535994315453806, 'colsample_bytree': 0.7709785907766107, 'gamma': 0.43969234733080975, 'min_child_weight': 3, 'scale_pos_weight': 0.5090681947688525}. Best is trial 0 with value: 0.6688870406382103.
C:\Users\timea\AppData\Local\Temp\ipykernel_13396\4213741627.py:5: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  "learning_rate": trial.suggest_loguniform("learning_rate", 0.01, 0.3),
C:\Users\timea\AppData\Local\Temp\ipykernel_13396\4213741627.py:6: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  "subsample": trial.suggest_uniform("subsample", 0.5, 1.0),
C:\Users\timea\AppData\Local\Temp\ipykernel_13396\4213741627.py:7: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  "colsample_bytree": trial.suggest_uniform("colsample_bytree", 0.5, 1.0),
C:\Users\timea\AppData\Local\Temp\ipykernel_13396\4213741627.py:8: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  "gamma": trial.suggest_loguniform("gamma", 1e-8, 1.0),
C:\Users\timea\AppData\Local\Temp\ipykernel_13396\4213741627.py:10: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  "scale_pos_weight": trial.suggest_loguniform("scale_pos_weight", 1e-2, 10),  # For handling imbalance
[I 2025-04-02 02:40:33,343] Trial 1 finished with value: 0.5398266022335807 and parameters: {'n_estimators': 689, 'max_depth': 14, 'learning_rate': 0.02505967686167853, 'subsample': 0.9969772312981886, 'colsample_bytree': 0.6061380105133198, 'gamma': 0.4383087626388966, 'min_child_weight': 8, 'scale_pos_weight': 0.30383205407940317}. Best is trial 0 with value: 0.6688870406382103.
C:\Users\timea\AppData\Local\Temp\ipykernel_13396\4213741627.py:5: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  "learning_rate": trial.suggest_loguniform("learning_rate", 0.01, 0.3),
C:\Users\timea\AppData\Local\Temp\ipykernel_13396\4213741627.py:6: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  "subsample": trial.suggest_uniform("subsample", 0.5, 1.0),
C:\Users\timea\AppData\Local\Temp\ipykernel_13396\4213741627.py:7: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  "colsample_bytree": trial.suggest_uniform("colsample_bytree", 0.5, 1.0),
C:\Users\timea\AppData\Local\Temp\ipykernel_13396\4213741627.py:8: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  "gamma": trial.suggest_loguniform("gamma", 1e-8, 1.0),
C:\Users\timea\AppData\Local\Temp\ipykernel_13396\4213741627.py:10: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  "scale_pos_weight": trial.suggest_loguniform("scale_pos_weight", 1e-2, 10),  # For handling imbalance
[I 2025-04-02 02:40:38,254] Trial 2 finished with value: 0.7115034866644042 and parameters: {'n_estimators': 210, 'max_depth': 15, 'learning_rate': 0.04714545331714752, 'subsample': 0.7975929616077773, 'colsample_bytree': 0.8074323410389219, 'gamma': 8.431331991528753e-06, 'min_child_weight': 4, 'scale_pos_weight': 3.963294489767259}. Best is trial 2 with value: 0.7115034866644042.
C:\Users\timea\AppData\Local\Temp\ipykernel_13396\4213741627.py:5: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  "learning_rate": trial.suggest_loguniform("learning_rate", 0.01, 0.3),
C:\Users\timea\AppData\Local\Temp\ipykernel_13396\4213741627.py:6: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  "subsample": trial.suggest_uniform("subsample", 0.5, 1.0),
C:\Users\timea\AppData\Local\Temp\ipykernel_13396\4213741627.py:7: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  "colsample_bytree": trial.suggest_uniform("colsample_bytree", 0.5, 1.0),
C:\Users\timea\AppData\Local\Temp\ipykernel_13396\4213741627.py:8: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  "gamma": trial.suggest_loguniform("gamma", 1e-8, 1.0),
C:\Users\timea\AppData\Local\Temp\ipykernel_13396\4213741627.py:10: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  "scale_pos_weight": trial.suggest_loguniform("scale_pos_weight", 1e-2, 10),  # For handling imbalance
[I 2025-04-02 02:40:48,130] Trial 3 finished with value: 0.6711807260873435 and parameters: {'n_estimators': 780, 'max_depth': 11, 'learning_rate': 0.17521231329712786, 'subsample': 0.5864057526043369, 'colsample_bytree': 0.6360751789115333, 'gamma': 0.02240456725618245, 'min_child_weight': 7, 'scale_pos_weight': 0.3297540120881839}. Best is trial 2 with value: 0.7115034866644042.
C:\Users\timea\AppData\Local\Temp\ipykernel_13396\4213741627.py:5: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  "learning_rate": trial.suggest_loguniform("learning_rate", 0.01, 0.3),
C:\Users\timea\AppData\Local\Temp\ipykernel_13396\4213741627.py:6: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  "subsample": trial.suggest_uniform("subsample", 0.5, 1.0),
C:\Users\timea\AppData\Local\Temp\ipykernel_13396\4213741627.py:7: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  "colsample_bytree": trial.suggest_uniform("colsample_bytree", 0.5, 1.0),
C:\Users\timea\AppData\Local\Temp\ipykernel_13396\4213741627.py:8: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  "gamma": trial.suggest_loguniform("gamma", 1e-8, 1.0),
C:\Users\timea\AppData\Local\Temp\ipykernel_13396\4213741627.py:10: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  "scale_pos_weight": trial.suggest_loguniform("scale_pos_weight", 1e-2, 10),  # For handling imbalance
[I 2025-04-02 02:40:54,681] Trial 4 finished with value: 0.5827679955662354 and parameters: {'n_estimators': 486, 'max_depth': 15, 'learning_rate': 0.02194717626325587, 'subsample': 0.5910183166622502, 'colsample_bytree': 0.990896373465614, 'gamma': 0.0010486834733562005, 'min_child_weight': 8, 'scale_pos_weight': 0.34994242056600994}. Best is trial 2 with value: 0.7115034866644042.
C:\Users\timea\AppData\Local\Temp\ipykernel_13396\4213741627.py:5: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  "learning_rate": trial.suggest_loguniform("learning_rate", 0.01, 0.3),
C:\Users\timea\AppData\Local\Temp\ipykernel_13396\4213741627.py:6: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  "subsample": trial.suggest_uniform("subsample", 0.5, 1.0),
C:\Users\timea\AppData\Local\Temp\ipykernel_13396\4213741627.py:7: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  "colsample_bytree": trial.suggest_uniform("colsample_bytree", 0.5, 1.0),
C:\Users\timea\AppData\Local\Temp\ipykernel_13396\4213741627.py:8: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  "gamma": trial.suggest_loguniform("gamma", 1e-8, 1.0),
C:\Users\timea\AppData\Local\Temp\ipykernel_13396\4213741627.py:10: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  "scale_pos_weight": trial.suggest_loguniform("scale_pos_weight", 1e-2, 10),  # For handling imbalance
[I 2025-04-02 02:41:06,680] Trial 5 finished with value: 0.6911824205402185 and parameters: {'n_estimators': 729, 'max_depth': 15, 'learning_rate': 0.12314363076364845, 'subsample': 0.5099659698956662, 'colsample_bytree': 0.8960531485289165, 'gamma': 0.0008626989003308916, 'min_child_weight': 4, 'scale_pos_weight': 1.4264653539071488}. Best is trial 2 with value: 0.7115034866644042.
C:\Users\timea\AppData\Local\Temp\ipykernel_13396\4213741627.py:5: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  "learning_rate": trial.suggest_loguniform("learning_rate", 0.01, 0.3),
C:\Users\timea\AppData\Local\Temp\ipykernel_13396\4213741627.py:6: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  "subsample": trial.suggest_uniform("subsample", 0.5, 1.0),
C:\Users\timea\AppData\Local\Temp\ipykernel_13396\4213741627.py:7: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  "colsample_bytree": trial.suggest_uniform("colsample_bytree", 0.5, 1.0),
C:\Users\timea\AppData\Local\Temp\ipykernel_13396\4213741627.py:8: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  "gamma": trial.suggest_loguniform("gamma", 1e-8, 1.0),
C:\Users\timea\AppData\Local\Temp\ipykernel_13396\4213741627.py:10: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  "scale_pos_weight": trial.suggest_loguniform("scale_pos_weight", 1e-2, 10),  # For handling imbalance
[I 2025-04-02 02:41:13,584] Trial 6 finished with value: 0.25345414193641636 and parameters: {'n_estimators': 651, 'max_depth': 7, 'learning_rate': 0.03206893324938728, 'subsample': 0.517836794496331, 'colsample_bytree': 0.5159051793518528, 'gamma': 1.1843700623555825e-05, 'min_child_weight': 1, 'scale_pos_weight': 0.06440845460105034}. Best is trial 2 with value: 0.7115034866644042.
C:\Users\timea\AppData\Local\Temp\ipykernel_13396\4213741627.py:5: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  "learning_rate": trial.suggest_loguniform("learning_rate", 0.01, 0.3),
C:\Users\timea\AppData\Local\Temp\ipykernel_13396\4213741627.py:6: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  "subsample": trial.suggest_uniform("subsample", 0.5, 1.0),
C:\Users\timea\AppData\Local\Temp\ipykernel_13396\4213741627.py:7: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  "colsample_bytree": trial.suggest_uniform("colsample_bytree", 0.5, 1.0),
C:\Users\timea\AppData\Local\Temp\ipykernel_13396\4213741627.py:8: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  "gamma": trial.suggest_loguniform("gamma", 1e-8, 1.0),
C:\Users\timea\AppData\Local\Temp\ipykernel_13396\4213741627.py:10: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  "scale_pos_weight": trial.suggest_loguniform("scale_pos_weight", 1e-2, 10),  # For handling imbalance
[I 2025-04-02 02:41:25,129] Trial 7 finished with value: 0.7146869640660792 and parameters: {'n_estimators': 613, 'max_depth': 12, 'learning_rate': 0.11984528437621646, 'subsample': 0.7978068609280746, 'colsample_bytree': 0.9236625578227469, 'gamma': 7.216424675815523e-05, 'min_child_weight': 1, 'scale_pos_weight': 5.970881507157039}. Best is trial 7 with value: 0.7146869640660792.
C:\Users\timea\AppData\Local\Temp\ipykernel_13396\4213741627.py:5: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  "learning_rate": trial.suggest_loguniform("learning_rate", 0.01, 0.3),
C:\Users\timea\AppData\Local\Temp\ipykernel_13396\4213741627.py:6: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  "subsample": trial.suggest_uniform("subsample", 0.5, 1.0),
C:\Users\timea\AppData\Local\Temp\ipykernel_13396\4213741627.py:7: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  "colsample_bytree": trial.suggest_uniform("colsample_bytree", 0.5, 1.0),
C:\Users\timea\AppData\Local\Temp\ipykernel_13396\4213741627.py:8: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  "gamma": trial.suggest_loguniform("gamma", 1e-8, 1.0),
C:\Users\timea\AppData\Local\Temp\ipykernel_13396\4213741627.py:10: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  "scale_pos_weight": trial.suggest_loguniform("scale_pos_weight", 1e-2, 10),  # For handling imbalance
[I 2025-04-02 02:41:29,377] Trial 8 finished with value: 0.7177776298965024 and parameters: {'n_estimators': 335, 'max_depth': 8, 'learning_rate': 0.056387448872015224, 'subsample': 0.7338941060269971, 'colsample_bytree': 0.8166809203484915, 'gamma': 0.0005159547270266709, 'min_child_weight': 9, 'scale_pos_weight': 3.5520686142797318}. Best is trial 8 with value: 0.7177776298965024.
C:\Users\timea\AppData\Local\Temp\ipykernel_13396\4213741627.py:5: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  "learning_rate": trial.suggest_loguniform("learning_rate", 0.01, 0.3),
C:\Users\timea\AppData\Local\Temp\ipykernel_13396\4213741627.py:6: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  "subsample": trial.suggest_uniform("subsample", 0.5, 1.0),
C:\Users\timea\AppData\Local\Temp\ipykernel_13396\4213741627.py:7: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  "colsample_bytree": trial.suggest_uniform("colsample_bytree", 0.5, 1.0),

Best trial:
  F1 Score: 0.7448064174874511
  Params:
    n_estimators: 916
    max_depth: 3
    learning_rate: 0.11070908761699479
    subsample: 0.8598999966015285
    colsample_bytree: 0.818100639999129
    gamma: 2.700066449998596e-08
    min_child_weight: 6
    scale_pos_weight: 1.5696875214477706

In [11]:
best_xgb = XGBClassifier(**best_trial.params, random_state=42, eval_metric="logloss", use_label_encoder=False)
best_xgb.fit(X_train, y_train)

y_pred_prob = best_xgb.predict_proba(X_test)[:, 1]
y_pred_binary = (y_pred_prob >= 0.5).astype(int)

test_f1 = f1_score(y_test, y_pred_binary, average="weighted")
print(f"Test F1 Score: {test_f1}")

c:\Python311\Lib\site-packages\xgboost\training.py:183: UserWarning: [02:51:53] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

Test F1 Score: 0.9183436697495492

In [12]:
results: list[dict] = []
results.append(get_metrics(y_test, y_pred_binary, "XGBoost"))

In [13]:
pickle.dump(best_xgb, open("models/xgb_cvd.pkl", "wb"))
xgb = pickle.load(open("models/xgb_cvd.pkl", "rb"))
y_pred_prob = xgb.predict_proba(X_test)[:, 1]
pl.DataFrame(get_metrics(y_test, (y_pred_prob >= 0.5).astype(int), "XGBoost"))

shape: (1, 6)
┌─────────┬──────────┬───────────┬──────────┬──────────┬──────────┐
│ Model   ┆ Accuracy ┆ Precision ┆ Recall   ┆ F1 Score ┆ ROC AUC  │
│ ---     ┆ ---      ┆ ---       ┆ ---      ┆ ---      ┆ ---      │
│ str     ┆ f64      ┆ f64       ┆ f64      ┆ f64      ┆ f64      │
╞═════════╪══════════╪═══════════╪══════════╪══════════╪══════════╡
│ XGBoost ┆ 0.91799  ┆ 0.740424  ┆ 0.756446 ┆ 0.748349 ┆ 0.852741 │
└─────────┴──────────┴───────────┴──────────┴──────────┴──────────┘

In [14]:
def objective(trial):
    params = {
        "n_estimators": trial.suggest_int("n_estimators", 100, 1000),
        "max_depth": trial.suggest_int("max_depth", 3, 15),
        "learning_rate": trial.suggest_loguniform("learning_rate", 0.01, 0.3),
        # LightGBM uses bagging_fraction (equivalent to subsample) and bagging_freq to enable bagging
        "bagging_fraction": trial.suggest_uniform("bagging_fraction", 0.5, 1.0),
        "feature_fraction": trial.suggest_uniform("feature_fraction", 0.5, 1.0),
        # min_split_gain is LightGBM's equivalent to gamma in XGBoost
        "min_split_gain": trial.suggest_loguniform("min_split_gain", 1e-8, 1.0),
        # min_child_samples corresponds to the minimum number of samples in a leaf
        "min_child_samples": trial.suggest_int("min_child_samples", 1, 10),
        "scale_pos_weight": trial.suggest_loguniform("scale_pos_weight", 1e-2, 10),  # For handling imbalance
        "random_state": 42,
        "eval_metric": "logloss",
    }

    skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
    model = LGBMClassifier(**params)
    scores = cross_val_score(model, X_train, y_train, cv=skf, scoring="f1", n_jobs=-1)
    return scores.mean()

# Create an Optuna study and optimize the objective
study = optuna.create_study(direction="maximize")
study.optimize(objective, n_trials=100)

# Print the best trial details
print("Best trial:")
best_trial = study.best_trial
print(f"  F1 Score: {best_trial.value}")
print("  Params:")
for key, value in best_trial.params.items():
    print(f"    {key}: {value}")

[I 2025-04-02 02:51:55,683] A new study created in memory with name: no-name-93e8c4b8-c7b7-4728-a901-a04e85f8f0e6
C:\Users\timea\AppData\Local\Temp\ipykernel_13396\3789400504.py:5: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  "learning_rate": trial.suggest_loguniform("learning_rate", 0.01, 0.3),
C:\Users\timea\AppData\Local\Temp\ipykernel_13396\3789400504.py:7: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  "bagging_fraction": trial.suggest_uniform("bagging_fraction", 0.5, 1.0),
C:\Users\timea\AppData\Local\Temp\ipykernel_13396\3789400504.py:8: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  "feature_fraction": trial.suggest_uniform("feature_fraction", 0.5, 1.0),
C:\Users\timea\AppData\Local\Temp\ipykernel_13396\3789400504.py:10: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  "min_split_gain": trial.suggest_loguniform("min_split_gain", 1e-8, 1.0),
C:\Users\timea\AppData\Local\Temp\ipykernel_13396\3789400504.py:13: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  "scale_pos_weight": trial.suggest_loguniform("scale_pos_weight", 1e-2, 10),  # For handling imbalance
[I 2025-04-02 02:52:04,822] Trial 0 finished with value: 0.7709688014438456 and parameters: {'n_estimators': 699, 'max_depth': 15, 'learning_rate': 0.13223800281137188, 'bagging_fraction': 0.852972233119452, 'feature_fraction': 0.6226525445141751, 'min_split_gain': 0.00034430622276380193, 'min_child_samples': 7, 'scale_pos_weight': 2.5362359676231794}. Best is trial 0 with value: 0.7709688014438456.
C:\Users\timea\AppData\Local\Temp\ipykernel_13396\3789400504.py:5: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  "learning_rate": trial.suggest_loguniform("learning_rate", 0.01, 0.3),
C:\Users\timea\AppData\Local\Temp\ipykernel_13396\3789400504.py:7: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  "bagging_fraction": trial.suggest_uniform("bagging_fraction", 0.5, 1.0),
C:\Users\timea\AppData\Local\Temp\ipykernel_13396\3789400504.py:8: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  "feature_fraction": trial.suggest_uniform("feature_fraction", 0.5, 1.0),
C:\Users\timea\AppData\Local\Temp\ipykernel_13396\3789400504.py:10: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  "min_split_gain": trial.suggest_loguniform("min_split_gain", 1e-8, 1.0),
C:\Users\timea\AppData\Local\Temp\ipykernel_13396\3789400504.py:13: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  "scale_pos_weight": trial.suggest_loguniform("scale_pos_weight", 1e-2, 10),  # For handling imbalance
[I 2025-04-02 02:52:17,649] Trial 1 finished with value: 0.7282726726405745 and parameters: {'n_estimators': 721, 'max_depth': 13, 'learning_rate': 0.03573607251083672, 'bagging_fraction': 0.6091758470217886, 'feature_fraction': 0.7671003455750371, 'min_split_gain': 3.756572198560314e-07, 'min_child_samples': 1, 'scale_pos_weight': 0.46103609770195}. Best is trial 0 with value: 0.7709688014438456.
C:\Users\timea\AppData\Local\Temp\ipykernel_13396\3789400504.py:5: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  "learning_rate": trial.suggest_loguniform("learning_rate", 0.01, 0.3),
C:\Users\timea\AppData\Local\Temp\ipykernel_13396\3789400504.py:7: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  "bagging_fraction": trial.suggest_uniform("bagging_fraction", 0.5, 1.0),
C:\Users\timea\AppData\Local\Temp\ipykernel_13396\3789400504.py:8: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  "feature_fraction": trial.suggest_uniform("feature_fraction", 0.5, 1.0),
C:\Users\timea\AppData\Local\Temp\ipykernel_13396\3789400504.py:10: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  "min_split_gain": trial.suggest_loguniform("min_split_gain", 1e-8, 1.0),
C:\Users\timea\AppData\Local\Temp\ipykernel_13396\3789400504.py:13: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  "scale_pos_weight": trial.suggest_loguniform("scale_pos_weight", 1e-2, 10),  # For handling imbalance
[I 2025-04-02 02:52:21,109] Trial 2 finished with value: 0.04322353931602234 and parameters: {'n_estimators': 271, 'max_depth': 14, 'learning_rate': 0.015978567028316137, 'bagging_fraction': 0.8005269460862184, 'feature_fraction': 0.6027324304646395, 'min_split_gain': 2.680509806287377e-07, 'min_child_samples': 10, 'scale_pos_weight': 0.036364813579085796}. Best is trial 0 with value: 0.7709688014438456.
C:\Users\timea\AppData\Local\Temp\ipykernel_13396\3789400504.py:5: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  "learning_rate": trial.suggest_loguniform("learning_rate", 0.01, 0.3),
C:\Users\timea\AppData\Local\Temp\ipykernel_13396\3789400504.py:7: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  "bagging_fraction": trial.suggest_uniform("bagging_fraction", 0.5, 1.0),
C:\Users\timea\AppData\Local\Temp\ipykernel_13396\3789400504.py:8: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  "feature_fraction": trial.suggest_uniform("feature_fraction", 0.5, 1.0),
C:\Users\timea\AppData\Local\Temp\ipykernel_13396\3789400504.py:10: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  "min_split_gain": trial.suggest_loguniform("min_split_gain", 1e-8, 1.0),
C:\Users\timea\AppData\Local\Temp\ipykernel_13396\3789400504.py:13: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  "scale_pos_weight": trial.suggest_loguniform("scale_pos_weight", 1e-2, 10),  # For handling imbalance
[I 2025-04-02 02:52:22,767] Trial 3 finished with value: 0.0018392134131530603 and parameters: {'n_estimators': 155, 'max_depth': 4, 'learning_rate': 0.01909594685105625, 'bagging_fraction': 0.8180586262760509, 'feature_fraction': 0.8948402443479646, 'min_split_gain': 0.00010354107984025771, 'min_child_samples': 5, 'scale_pos_weight': 0.2914042038034989}. Best is trial 0 with value: 0.7709688014438456.
C:\Users\timea\AppData\Local\Temp\ipykernel_13396\3789400504.py:5: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  "learning_rate": trial.suggest_loguniform("learning_rate", 0.01, 0.3),
C:\Users\timea\AppData\Local\Temp\ipykernel_13396\3789400504.py:7: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  "bagging_fraction": trial.suggest_uniform("bagging_fraction", 0.5, 1.0),
C:\Users\timea\AppData\Local\Temp\ipykernel_13396\3789400504.py:8: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  "feature_fraction": trial.suggest_uniform("feature_fraction", 0.5, 1.0),
C:\Users\timea\AppData\Local\Temp\ipykernel_13396\3789400504.py:10: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  "min_split_gain": trial.suggest_loguniform("min_split_gain", 1e-8, 1.0),
C:\Users\timea\AppData\Local\Temp\ipykernel_13396\3789400504.py:13: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  "scale_pos_weight": trial.suggest_loguniform("scale_pos_weight", 1e-2, 10),  # For handling imbalance
[I 2025-04-02 02:52:36,124] Trial 4 finished with value: 0.6147713845400438 and parameters: {'n_estimators': 905, 'max_depth': 14, 'learning_rate': 0.041039800637645035, 'bagging_fraction': 0.8812076116028613, 'feature_fraction': 0.6366076158752424, 'min_split_gain': 0.0018334834947142773, 'min_child_samples': 3, 'scale_pos_weight': 0.013801021038180372}. Best is trial 0 with value: 0.7709688014438456.
C:\Users\timea\AppData\Local\Temp\ipykernel_13396\3789400504.py:5: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  "learning_rate": trial.suggest_loguniform("learning_rate", 0.01, 0.3),
C:\Users\timea\AppData\Local\Temp\ipykernel_13396\3789400504.py:7: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  "bagging_fraction": trial.suggest_uniform("bagging_fraction", 0.5, 1.0),
C:\Users\timea\AppData\Local\Temp\ipykernel_13396\3789400504.py:8: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  "feature_fraction": trial.suggest_uniform("feature_fraction", 0.5, 1.0),
C:\Users\timea\AppData\Local\Temp\ipykernel_13396\3789400504.py:10: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  "min_split_gain": trial.suggest_loguniform("min_split_gain", 1e-8, 1.0),
C:\Users\timea\AppData\Local\Temp\ipykernel_13396\3789400504.py:13: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  "scale_pos_weight": trial.suggest_loguniform("scale_pos_weight", 1e-2, 10),  # For handling imbalance
[I 2025-04-02 02:52:42,836] Trial 5 finished with value: 0.7696874992237935 and parameters: {'n_estimators': 558, 'max_depth': 14, 'learning_rate': 0.1314152088475879, 'bagging_fraction': 0.6090408750370473, 'feature_fraction': 0.8991751362427678, 'min_split_gain': 0.000351025824737501, 'min_child_samples': 1, 'scale_pos_weight': 2.3929349210782873}. Best is trial 0 with value: 0.7709688014438456.
C:\Users\timea\AppData\Local\Temp\ipykernel_13396\3789400504.py:5: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  "learning_rate": trial.suggest_loguniform("learning_rate", 0.01, 0.3),
C:\Users\timea\AppData\Local\Temp\ipykernel_13396\3789400504.py:7: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  "bagging_fraction": trial.suggest_uniform("bagging_fraction", 0.5, 1.0),
C:\Users\timea\AppData\Local\Temp\ipykernel_13396\3789400504.py:8: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  "feature_fraction": trial.suggest_uniform("feature_fraction", 0.5, 1.0),
C:\Users\timea\AppData\Local\Temp\ipykernel_13396\3789400504.py:10: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  "min_split_gain": trial.suggest_loguniform("min_split_gain", 1e-8, 1.0),
C:\Users\timea\AppData\Local\Temp\ipykernel_13396\3789400504.py:13: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  "scale_pos_weight": trial.suggest_loguniform("scale_pos_weight", 1e-2, 10),  # For handling imbalance
[I 2025-04-02 02:52:48,016] Trial 6 finished with value: 0.6584124909393291 and parameters: {'n_estimators': 512, 'max_depth': 7, 'learning_rate': 0.015032623420329861, 'bagging_fraction': 0.9230667653223936, 'feature_fraction': 0.7210572098890373, 'min_split_gain': 0.13936117507055487, 'min_child_samples': 7, 'scale_pos_weight': 4.588504448752617}. Best is trial 0 with value: 0.7709688014438456.
C:\Users\timea\AppData\Local\Temp\ipykernel_13396\3789400504.py:5: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  "learning_rate": trial.suggest_loguniform("learning_rate", 0.01, 0.3),
C:\Users\timea\AppData\Local\Temp\ipykernel_13396\3789400504.py:7: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  "bagging_fraction": trial.suggest_uniform("bagging_fraction", 0.5, 1.0),
C:\Users\timea\AppData\Local\Temp\ipykernel_13396\3789400504.py:8: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  "feature_fraction": trial.suggest_uniform("feature_fraction", 0.5, 1.0),
C:\Users\timea\AppData\Local\Temp\ipykernel_13396\3789400504.py:10: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  "min_split_gain": trial.suggest_loguniform("min_split_gain", 1e-8, 1.0),
C:\Users\timea\AppData\Local\Temp\ipykernel_13396\3789400504.py:13: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  "scale_pos_weight": trial.suggest_loguniform("scale_pos_weight", 1e-2, 10),  # For handling imbalance
[I 2025-04-02 02:52:51,216] Trial 7 finished with value: 0.7286807377940916 and parameters: {'n_estimators': 265, 'max_depth': 9, 'learning_rate': 0.16872807263931022, 'bagging_fraction': 0.6477589181276078, 'feature_fraction': 0.9434484812637007, 'min_split_gain': 0.00169124402722408, 'min_child_samples': 6, 'scale_pos_weight': 5.883283788998218}. Best is trial 0 with value: 0.7709688014438456.
C:\Users\timea\AppData\Local\Temp\ipykernel_13396\3789400504.py:5: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  "learning_rate": trial.suggest_loguniform("learning_rate", 0.01, 0.3),
C:\Users\timea\AppData\Local\Temp\ipykernel_13396\3789400504.py:7: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  "bagging_fraction": trial.suggest_uniform("bagging_fraction", 0.5, 1.0),
C:\Users\timea\AppData\Local\Temp\ipykernel_13396\3789400504.py:8: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  "feature_fraction": trial.suggest_uniform("feature_fraction", 0.5, 1.0),
C:\Users\timea\AppData\Local\Temp\ipykernel_13396\3789400504.py:10: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  "min_split_gain": trial.suggest_loguniform("min_split_gain", 1e-8, 1.0),
C:\Users\timea\AppData\Local\Temp\ipykernel_13396\3789400504.py:13: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  "scale_pos_weight": trial.suggest_loguniform("scale_pos_weight", 1e-2, 10),  # For handling imbalance
[I 2025-04-02 02:53:00,908] Trial 8 finished with value: 0.7040889727172596 and parameters: {'n_estimators': 566, 'max_depth': 13, 'learning_rate': 0.03561303520347881, 'bagging_fraction': 0.946958556679801, 'feature_fraction': 0.7187040633656574, 'min_split_gain': 1.714139205650199e-05, 'min_child_samples': 5, 'scale_pos_weight': 0.3629744853933483}. Best is trial 0 with value: 0.7709688014438456.
C:\Users\timea\AppData\Local\Temp\ipykernel_13396\3789400504.py:5: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  "learning_rate": trial.suggest_loguniform("learning_rate", 0.01, 0.3),
C:\Users\timea\AppData\Local\Temp\ipykernel_13396\3789400504.py:7: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  "bagging_fraction": trial.suggest_uniform("bagging_fraction", 0.5, 1.0),

Best trial:
  F1 Score: 0.7901560459068031
  Params:
    n_estimators: 1000
    max_depth: 3
    learning_rate: 0.22085448795151694
    bagging_fraction: 0.711906787934381
    feature_fraction: 0.5003764870964829
    min_split_gain: 0.0012352978938123577
    min_child_samples: 10
    scale_pos_weight: 1.2792573965183194

In [15]:
best_lgb = LGBMClassifier(**best_trial.params, random_state=42, eval_metric="logloss")
best_lgb.fit(X_train, y_train)

y_pred_prob: np.ndarray = best_lgb.predict_proba(X_test)[:, 1]
y_pred_binary:  np.ndarray = (y_pred_prob >= 0.5).astype(int)
test_f1: float = f1_score(y_test, y_pred_binary, average="weighted")
print(f"Test F1 Score: {test_f1}")

[LightGBM] [Warning] Unknown parameter: eval_metric
[LightGBM] [Warning] feature_fraction is set=0.5003764870964829, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.5003764870964829
[LightGBM] [Warning] bagging_fraction is set=0.711906787934381, subsample=1.0 will be ignored. Current value: bagging_fraction=0.711906787934381
[LightGBM] [Warning] Unknown parameter: eval_metric
[LightGBM] [Warning] feature_fraction is set=0.5003764870964829, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.5003764870964829
[LightGBM] [Warning] bagging_fraction is set=0.711906787934381, subsample=1.0 will be ignored. Current value: bagging_fraction=0.711906787934381
[LightGBM] [Info] Number of positive: 8686, number of negative: 45208
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.006746 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 696
[LightGBM] [Info] Number of data points in the train set: 53894, number of used features: 23
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.161168 -> initscore=-1.649562
[LightGBM] [Info] Start training from score -1.649562
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

In [16]:
results.append(get_metrics(y_test, y_pred_binary, "LightGBM"))

In [17]:
pickle.dump(best_lgb, open("models/lightgbm_cvd.pkl", "wb"))
lgb: LGBMClassifier = pickle.load(open("models/lightgbm_cvd.pkl", "rb"))
y_pred_prob: np.ndarray = lgb.predict_proba(X_test)[:, 1]
y_pred_binary:  np.ndarray = (y_pred_prob >= 0.5).astype(int)
pl.DataFrame(get_metrics(y_test, y_pred_binary, "LightGBM"))

[LightGBM] [Warning] Unknown parameter: eval_metric
[LightGBM] [Warning] feature_fraction is set=0.5003764870964829, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.5003764870964829
[LightGBM] [Warning] bagging_fraction is set=0.711906787934381, subsample=1.0 will be ignored. Current value: bagging_fraction=0.711906787934381

shape: (1, 6)
┌──────────┬──────────┬───────────┬──────────┬──────────┬──────────┐
│ Model    ┆ Accuracy ┆ Precision ┆ Recall   ┆ F1 Score ┆ ROC AUC  │
│ ---      ┆ ---      ┆ ---       ┆ ---      ┆ ---      ┆ ---      │
│ str      ┆ f64      ┆ f64       ┆ f64      ┆ f64      ┆ f64      │
╞══════════╪══════════╪═══════════╪══════════╪══════════╪══════════╡
│ LightGBM ┆ 0.934689 ┆ 0.825605  ┆ 0.754144 ┆ 0.788258 ┆ 0.861765 │
└──────────┴──────────┴───────────┴──────────┴──────────┴──────────┘

In [18]:
df = pl.DataFrame(results)
df

shape: (2, 6)
┌──────────┬──────────┬───────────┬──────────┬──────────┬──────────┐
│ Model    ┆ Accuracy ┆ Precision ┆ Recall   ┆ F1 Score ┆ ROC AUC  │
│ ---      ┆ ---      ┆ ---       ┆ ---      ┆ ---      ┆ ---      │
│ str      ┆ f64      ┆ f64       ┆ f64      ┆ f64      ┆ f64      │
╞══════════╪══════════╪═══════════╪══════════╪══════════╪══════════╡
│ XGBoost  ┆ 0.91799  ┆ 0.740424  ┆ 0.756446 ┆ 0.748349 ┆ 0.852741 │
│ LightGBM ┆ 0.934689 ┆ 0.825605  ┆ 0.754144 ┆ 0.788258 ┆ 0.861765 │
└──────────┴──────────┴───────────┴──────────┴──────────┴──────────┘